config/routes.rb
Rails.application.routes.draw do
  resources :anon_customers
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anon_customer.rb
class AnonCustomer < ApplicationRecord
    validates_presence_of :first_name
    # establish_connection DATA_ANON_NEW_DB
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/anon_customers_controller.rb
class AnonCustomersController < ApplicationController
  before_action :set_anon_customer, only: [:show, :edit, :update, :destroy]

  # GET /anon_customers
  # GET /anon_customers.json
  def index
    @anon_customers = AnonCustomer.all
  end

  # GET /anon_customers/1
  # GET /anon_customers/1.json
  def show
  end

  # GET /anon_customers/new
  def new
    @anon_customer = AnonCustomer.new
  end

  # GET /anon_customers/1/edit
  def edit
  end

  # POST /anon_customers
  # POST /anon_customers.json
  def create
    @anon_customer = AnonCustomer.new(anon_customer_params)

    respond_to do |format|
      if @anon_customer.save
        format.html { redirect_to @anon_customer, notice: 'Anon customer was successfully created.' }
        format.json { render :show, status: :created, location: @anon_customer }
      else
        format.html { render :new }
        format.json { render json: @anon_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anon_customers/1
  # PATCH/PUT /anon_customers/1.json
  def update
    respond_to do |format|
      if @anon_customer.update(anon_customer_params)
        format.html { redirect_to @anon_customer, notice: 'Anon customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @anon_customer }
      else
        format.html { render :edit }
        format.json { render json: @anon_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anon_customers/1
  # DELETE /anon_customers/1.json
  def destroy
    @anon_customer.destroy
    respond_to do |format|
      format.html { redirect_to anon_customers_url, notice: 'Anon customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anon_customer
      @anon_customer = AnonCustomer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anon_customer_params
      params.require(:anon_customer).permit(:first_name, :last_name, :address1, :address2, :postcode, :state, :phone, :creditcard, :city, :birthday)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :address1, :address2, :state, :postcode, :email, :phone, :creditcard, :birthday)
    end
end

app/helpers/anon_customers_helper.rb
module AnonCustomersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/anon_customers/_form.html.erb
<%= form_with(model: anon_customer, local: true) do |form| %>
  <% if anon_customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anon_customer.errors.count, "error") %> prohibited this anon_customer from being saved:</h2>

      <ul>
      <% anon_customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :anon_customer_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :anon_customer_last_name %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :anon_customer_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :anon_customer_address2 %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :anon_customer_postcode %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :anon_customer_state %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :anon_customer_phone %>
  </div>

  <div class="field">
    <%= form.label :creditcard %>
    <%= form.text_field :creditcard, id: :anon_customer_creditcard %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :anon_customer_city %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :anon_customer_birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/anon_customers/edit.html.erb
<h1>Editing Anon Customer</h1>

<%= render 'form', anon_customer: @anon_customer %>

<%= link_to 'Show', @anon_customer %> |
<%= link_to 'Back', anon_customers_path %>

app/views/anon_customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anon Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Phone</th>
      <th>Creditcard</th>
      <th>City</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anon_customers.each do |anon_customer| %>
      <tr>
        <td><%= anon_customer.first_name %></td>
        <td><%= anon_customer.last_name %></td>
        <td><%= anon_customer.address1 %></td>
        <td><%= anon_customer.address2 %></td>
        <td><%= anon_customer.postcode %></td>
        <td><%= anon_customer.state %></td>
        <td><%= anon_customer.phone %></td>
        <td><%= anon_customer.creditcard %></td>
        <td><%= anon_customer.city %></td>
        <td><%= anon_customer.birthday %></td>
        <td><%= link_to 'Show', anon_customer %></td>
        <td><%= link_to 'Edit', edit_anon_customer_path(anon_customer) %></td>
        <td><%= link_to 'Destroy', anon_customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anon Customer', new_anon_customer_path %>

app/views/anon_customers/new.html.erb
<h1>New Anon Customer</h1>

<%= render 'form', anon_customer: @anon_customer %>

<%= link_to 'Back', anon_customers_path %>

app/views/anon_customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @anon_customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @anon_customer.last_name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @anon_customer.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @anon_customer.address2 %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @anon_customer.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @anon_customer.state %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @anon_customer.phone %>
</p>

<p>
  <strong>Creditcard:</strong>
  <%= @anon_customer.creditcard %>
</p>

<p>
  <strong>City:</strong>
  <%= @anon_customer.city %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @anon_customer.birthday %>
</p>

<%= link_to 'Edit', edit_anon_customer_path(@anon_customer) %> |
<%= link_to 'Back', anon_customers_path %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :customer_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :customer_last_name %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :customer_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :customer_address2 %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :customer_state %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :customer_postcode %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :customer_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :customer_phone %>
  </div>

  <div class="field">
    <%= form.label :creditcard %>
    <%= form.text_field :creditcard, id: :customer_creditcard %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_field :birthday, id: :customer_birthday %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Creditcard</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.address1 %></td>
        <td><%= customer.address2 %></td>
        <td><%= customer.state %></td>
        <td><%= customer.postcode %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.creditcard %></td>
        <td><%= customer.birthday %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @customer.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @customer.address2 %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @customer.postcode %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Creditcard:</strong>
  <%= @customer.creditcard %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @customer.birthday %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataAnon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>